spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/avexadoFarm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: seuEmail
    password: seuEmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

avexado-farm:
  token:
    segredo: segredo-aqui
    expiracao: 86400000

