spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/avexadoFarm}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false

server:
  port: 8080